using Discord;
using Discord.Interactions;
using Discord.WebSocket;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using MuzakBot.App.Modules;

namespace MuzakBot.App.Services;

/// <summary>
/// The service for interacting with Discord.
/// </summary>
public class DiscordService : IDiscordService
{
    private readonly DiscordSocketClient _discordSocketClient;
    private readonly ILogger<DiscordService> _logger;
    private readonly IConfiguration _config;
    private readonly IServiceProvider _serviceProvider;

    public DiscordService(DiscordSocketClient discordSocketClient, ILogger<DiscordService> logger, IConfiguration config, IServiceProvider serviceProvider)
    {
        _discordSocketClient = discordSocketClient;
        _logger = logger;
        _config = config;
        _serviceProvider = serviceProvider;
    }

    private InteractionService? _interactionService;

    /// <inheritdoc cref="IDiscordService.ConnectAsync"/>
    public async Task ConnectAsync()
    {
        // Log into Discord
        _logger.LogInformation("Connecting to Discord...");

        if (_config.GetValue<string>("DiscordClientToken") is null)
        {
            Exception errorException = new("DiscordClientToken is null. Please set the DiscordClientToken environment variable.");

            _logger.LogError(errorException, "{ErrorMessage}", errorException.Message);
            throw errorException;
        }

        await _discordSocketClient.LoginAsync(
            tokenType: TokenType.Bot,
            token: _config.GetValue<string>("DiscordClientToken")
        );

        await _discordSocketClient.StartAsync();

        // Initialize Discord Interaction Service
        _logger.LogInformation("Initializing Discord Interaction Service...");
        _interactionService = new(_discordSocketClient.Rest);

        await _interactionService.AddModuleAsync<ShareMusicCommandModule>(_serviceProvider);

        // Add logging to the DiscordSocketClient and InteractionService
        _discordSocketClient.Log += HandleLog;
        _interactionService.Log += HandleLog;

        // Add slash command handler
        _discordSocketClient.InteractionCreated += HandleSlashCommand;

        // Add ready handler
        _discordSocketClient.Ready += OnClientReadyAsync;
    }

    /// <summary>
    /// Called when the Discord client is ready.
    /// <list type="table">
    ///     <listheader>
    ///         <term>Task</term>
    ///         <description>Description</description>
    ///     </listheader>
    ///     <item>
    ///         <term>Register commands</term>
    ///         <description>Registers slash commands to the test guild if in debug mode, otherwise registers slash commands globally.</description>
    ///     </item>
    /// </list>
    /// </summary>
    private async Task OnClientReadyAsync()
    {
#if DEBUG
        ulong testGuildId = _config.GetValue<ulong>("DiscordTestGuildId");
        _logger.LogInformation("Running in debug mode. Registering slash commands to test guild '{GuildId}'.", testGuildId);
        await _interactionService!.RegisterCommandsToGuildAsync(
            guildId: testGuildId,
            deleteMissing: true
        );
#else
        _logger.LogInformation("Registering slash commands globally.");
        await _interactionService!.RegisterCommandsGloballyAsync(
            deleteMissing: true
        );
#endif

        string slashCommandsLoadedString = string.Join(",", _interactionService.SlashCommands);
        _logger.LogInformation("Slash commands loaded: {SlashCommandsLoaded}", slashCommandsLoadedString);
    }

    /// <summary>
    /// Handler for the interaction service when a slash command is received.
    /// </summary>
    /// <param name="interaction">Interaction received from Discord's WebSocket API.</param>
    private async Task HandleSlashCommand(SocketInteraction interaction)
    {
        SocketInteractionContext interactionContext = new(_discordSocketClient, interaction);
        await _interactionService!.ExecuteCommandAsync(interactionContext, _serviceProvider);
    }

    /// <summary>
    /// Handler for outputting log messages from <see cref="DiscordSocketClient"/> and <see cref="InteractionService"/>
    /// to the dependency injected logger.
    /// </summary>
    /// <param name="logMessage">The log message generated by the Discord client.</param>
    /// <returns></returns>
    private Task HandleLog(LogMessage logMessage)
    {
        _logger.LogInformation("[{Severity}] {LogMessage}", logMessage.Severity, logMessage.ToString());

        return Task.CompletedTask;
    }

}