using Discord;
using Discord.Interactions;
using MuzakBot.App.Models.Odesli;
using MuzakBot.App.Services;
using Microsoft.Extensions.Logging;

namespace MuzakBot.App.Modules;

public partial class ShareMusicCommandModule
{
    [ComponentInteraction(customId: "remove-sharemusic-post-btn-*")]
    private async Task HandleMusicShareMessageRemovalAsync()
    {
        _logger.LogInformation("User requesting deletion: {requestingUser} | Original user: {originalUser}", Context.User.Id.ToString(), Context.Interaction.User.Id.ToString());
        if (Context.User.Id != Context.Interaction.User.Id)
        {
            await RespondAsync(
                text: "‼️ You're not allowed to delete a message not generated by you!",
                ephemeral: true
            );

            return;
        }

        await DeferAsync();

        _logger.LogInformation("Removing music share message '{id}'. Initiated by '{username}'", Context.Interaction.Id.ToString(), Context.User.Username);

        await DeleteOriginalResponseAsync();
    }
}