// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MuzakBot.Database;

#nullable disable

namespace MuzakBot.Database.Migrations
{
    [DbContext(typeof(LyricsAnalyzerContext))]
    partial class LyricsAnalyzerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.3");

            modelBuilder.Entity("MuzakBot.Lib.Models.Database.LyricsAnalyzer.LyricsAnalyzerConfig", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<string>("CommandDisabledGuildIds")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "commandDisabledGuildIds");

                    b.Property<string>("CommandEnabledGuildIds")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "commandEnabledGuildIds");

                    b.Property<bool>("CommandIsEnabledToSpecificGuilds")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "commandIsEnabledToSpecificGuilds");

                    b.Property<string>("PartitionKey")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "partitionKey");

                    b.Property<bool>("RateLimitEnabled")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "rateLimitEnabled");

                    b.Property<string>("RateLimitIgnoredUserIds")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "rateLimitIgnoredUserIds");

                    b.Property<int>("RateLimitMaxRequests")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "rateLimitMaxRequests");

                    b.HasKey("Id");

                    b.ToTable("Configs");
                });

            modelBuilder.Entity("MuzakBot.Lib.Models.Database.LyricsAnalyzer.LyricsAnalyzerPromptStyle", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<string>("AnalysisType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "analysisType");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "createdOn");

                    b.Property<DateTimeOffset>("LastUpdated")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "lastUpdated");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "name");

                    b.Property<string>("NoticeText")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "noticeText");

                    b.Property<string>("PartitionKey")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "partitionKey");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "prompt");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "shortName");

                    b.Property<string>("UserPrompt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PromptStyles");
                });

            modelBuilder.Entity("MuzakBot.Lib.Models.Database.LyricsAnalyzer.LyricsAnalyzerUserRateLimit", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<int>("CurrentRequestCount")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "currentRequestCount");

                    b.Property<DateTimeOffset>("LastRequestTime")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "lastRequestTime");

                    b.Property<string>("PartitionKey")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "partitionKey");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "userId");

                    b.HasKey("Id");

                    b.ToTable("UserRateLimits");
                });

            modelBuilder.Entity("MuzakBot.Lib.Models.Database.LyricsAnalyzer.SongLyricsItem", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<string>("ArtistName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "artistName");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "createdAt");

                    b.Property<string>("Lyrics")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "lyrics");

                    b.Property<string>("PartitionKey")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "partitionKey");

                    b.Property<string>("SongName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "songName");

                    b.HasKey("Id");

                    b.ToTable("SongLyrics");
                });
#pragma warning restore 612, 618
        }
    }
}
