name: "muzakbot-db-dev"

services:
  postgres:
    container_name: postgres
    image: docker.io/library/postgres:17-bookworm
    restart: always
    env_file: .env
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      PGDATA: "/var/lib/postgresql/data/pgdata"
      POSTGRES_HOST_AUTH_METHOD: "scram-sha-256"
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256"
    ports:
      - "8000:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
