# yaml-language-server: $schema=https://json.schemastore.org/github-workflow
name: Build
on:
  push:
    branches:
      - main
    paths-ignore:
      - "README.md"
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: ["./src/App/", "./src/Lib/", "./src/Lib.Services/"]
    env:
      DOTNET_NOLOGO: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup dotnet SDK
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json

      - name: Run 'dotnet restore'
        run: dotnet restore ${{ matrix.project}}

      - name: Run 'dotnet build'
        run: dotnet build ${{ matrix.project }} --configuration Release
