# yaml-language-server: $schema=https://json.schemastore.org/github-workflow
name: Build
on:
  push:
    paths-ignore:
      - "README.md"
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      DOTNET_NOLOGO: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup dotnet SDK
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json

      - name: Run 'dotnet restore'
        run: dotnet restore ./src/App/

      - name: Run 'dotnet build'
        run: dotnet build ./src/App/ --configuration Release