# yaml-language-server: $schema=https://json.schemastore.org/github-workflow
name: Build
on:
  push:
    branches:
      - main
    paths-ignore:
      - "README.md"
  pull_request:
  workflow_dispatch:

permissions:
  packages: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: ["./src/App/", "./src/GeniusService/", "./src/WebApp/" ]
    env:
      DOTNET_NOLOGO: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup dotnet SDK
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json
          cache: true

      - name: Configure 'smalls1652-github' NuGet feed
        run: dotnet nuget update source smalls1652-github --username "${{ github.repository_owner }}" --password "${{ secrets.GITHUB_TOKEN }}" --store-password-in-clear-text

      - name: Run 'dotnet restore'
        run: dotnet restore ${{ matrix.project }} --locked-mode

      - name: Run 'dotnet build'
        run: dotnet build ${{ matrix.project }} --configuration Release
