# yaml-language-server: $schema=https://json.schemastore.org/github-workflow
name: Create container image
on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

permissions:
  packages: write
  contents: read

jobs:
  create-container-image:
    name: Create container image
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          global-json-file: global.json

      - name: Install .NET tools
        run: dotnet tool restore

      - name: Update project files with gitversion
        run: dotnet tool run dotnet-gitversion /updateprojectfiles

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log into container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.actor }}/MuzakBot
          tags: |
            type=ref,event=tag
            type=ref,event=branch
            type=sha
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            "GITHUB_USER=${{ github.actor }}"
            "GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}"