# yaml-language-server: $schema=https://json.schemastore.org/github-workflow
name: Dependabot / Lockfile update

on:
    workflow_run: 
        branches: 
            - "dependabot/nuget/**"
        workflows: 
            - "Build"
        types: 
            - completed

permissions:
    contents: write
    pull-requests: write
    packages: read

jobs:
    update-lockfiles:
        name: Update lockfiles
        runs-on: ubuntu-latest
        env:
            DOTNET_NOLOGO: true

        if: ${{ github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'failure' }}

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              if: ${{ github.event_name != 'workflow_run' }}
              with:
                  fetch-depth: 0

            - name: Checkout repository (Specific branch)
              uses: actions/checkout@v4
              if: ${{ github.event_name == 'workflow_run' }}
              with:
                fetch-depth: 0
                ref: ${{ github.event.workflow_run.head_branch }}

            - name: Setup dotnet SDK
              uses: actions/setup-dotnet@v4
              with:
                  global-json-file: global.json

            - name: Configure 'smalls1652-github' NuGet feed
              run: |
                  dotnet nuget update source smalls1652-github --username "${{ github.repository_owner }}" --password "${{ secrets.GITHUB_TOKEN }}" --store-password-in-clear-text

            - name: Run 'dotnet restore --force-evaluate'
              run: |
                  dotnet restore --force-evaluate

            - name: Check for new changes
              id: diffcheck
              continue-on-error: true
              run: |
                  git add --intent-to-add .
                  git diff --name-only --exit-code

            - name: Push new changes
              if: steps.diffcheck.outcome == 'failure'
              run: |
                  git config user.email "${{ github.event.workflow_run.head_commit.author.email }}"
                  git config user.name "${{ github.event.workflow_run.head_commit.author.name }}"
                  git add .
                  git commit --amend --no-edit
                  git push origin --force
